<?php
$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image/') !== false)) {
        $lightMedia[] = $media;
    } elseif ((strpos($media->renderer(), 'youtube') !== false)) {
        $videoMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
$mediaExtent = [];
$tdExt = array('ply', 'nxs', 'nxz');
$imgExt = array('image/jpeg', 'image/png');
$gisExt = array("geojson");
?>

<?php $this->trigger('view.show.before'); ?>

<div class="testContent">

<div class="testHalf">
<div class="contentType">
<hr>
<h1><i class="fas fa-cube"></i></h1>
<hr>
</div>
<div class="value paragraphTitle">
<div class="titleMenu">
<div id="menuTitle topTitle">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
</div>
</div>
</div>
<hr>
<div class="allValues">
<?php echo $item->displayValues(); ?>
<?php if (count($otherMedia) > 0): ?>
 <div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="values">
        <?php foreach($otherMedia as $media): ?>
        <div class="value">
            <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
        </div>
    
    <?php endforeach; ?>
</div>
</div>
<?php endif; ?>

<hr>

<!-- pagination -->

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 100, $property);
?>

<!-- item linked items -->

<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
<hr>
</div>
</div>

<!-- item 3D models -->

<?php $template = 'omeka/site/item/show-default-models.phtml'; ?>
<?= $this->partial($template, $this->vars()) ?>
</div>
</div>
