<?php
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headLink()->appendStylesheet('//unpkg.com/leaflet@1.7.1/dist/leaflet.css');
$this->headLink()->appendStylesheet('//api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css');
$this->headScript()->appendFile('//unpkg.com/leaflet@1.7.1/dist/leaflet.js');
$this->headScript()->appendFile('//api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js');
$this->headScript()->appendFile('//unpkg.com/georaster-layer-for-leaflet/dist/georaster-layer-for-leaflet.min.js');
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js'));
?>
<div id="testMap">
    <div id="map">
    </div>
</div>

<script type="text/javascript">

// map creation

var map = new L.map('map', {
    maxZoom:26,
    minZoom:4,
    //fullscreenControl: true,
    fullscreenControl: {
        pseudoFullscreen: true,
        position: 'topright' // if true, fullscreen to page width and height
    }
});

map.scrollWheelZoom.disable();

map.once('focus', function() { map.scrollWheelZoom.enable(); });

// OSM map

var osm = new L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
});

// Positron Map

var CartoDB_Positron = L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
	subdomains: 'abcd',
	maxZoom: 19
}).addTo(map);

var Esri = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
				attribution: 'Tiles &copy; Esri'
});

// geojson definition

<?php 
    foreach ($item->media() as $reportGisDatasetSet):
        if ($reportGisDatasetSet->extension() == "geojson"):
            $a = $reportGisDatasetSet->id();
            $geojsonLayer = 'geojsonLayer'.$a;
            $layer = 'layer'.$a;
            $layer = file_get_contents($reportGisDatasetSet->originalUrl(), true); ?>
            var <?php echo $geojsonLayer ?> = <?php echo $layer; ?>;

<?php
        endif;
    endforeach;
?>

// layers definition

var geojsonMarkerOptions = {
            radius: 4,
            fillColor: "darkred",
            color: "#000",
            weight: 0,
            opacity: 1,
            fillOpacity: 0.8
        };

function generalStyle(feature) {
    return {
        weight: 1,
        color: '#000000',
        fillColor: 'darkred',
        dashArray: '',
        lineCap: 'square',
        lineJoin: 'bevel',
        opacity: 0.5,
        fillOpacity: 0.5
    };
}

<?php 
            foreach ($item->media() as $reportGisDatasetSet):
                if ($reportGisDatasetSet->extension() == "geojson"):
                    $a = $reportGisDatasetSet->id();
                    $layerAdded = 'layerAdded'.$a;
                    $geojsonLayer = 'geojsonLayer'.$a;
?>
var <?php echo $layerAdded ?> = new L.geoJSON(<?php echo $geojsonLayer ?>, {
    pointToLayer: function (feature, latlng) {
    return L.circleMarker(latlng, geojsonMarkerOptions);
    },
    style: generalStyle,
    onEachFeature: function (f, l) {
    l.bindPopup('<pre class="gisTooltip">'+JSON.stringify(f.properties,null,' ').replace(/[\{\}"]/g,'')+'</pre>');
    }
});

<?php 
                endif;
            endforeach;

?>

// layers group

var groupLayer = new L.layerGroup()

<?php 
            foreach ($item->media() as $reportGisDatasetSet):
                if ($reportGisDatasetSet->extension() == "geojson"):
                    $a = $reportGisDatasetSet->id();
                    $layerAdded = 'layerAdded'.$a;
?>
.addLayer(<?php echo $layerAdded ?>)

<?php
                endif;
            endforeach; 
?>

;


// features group

var groupFeature = new L.featureGroup([

<?php
            foreach ($item->media() as $reportGisDatasetSet):
                if ($reportGisDatasetSet->extension() == "geojson"):
                    $a = $reportGisDatasetSet->id();
                    $layerAdded = 'layerAdded'.$a;
                    echo $layerAdded.', ';
                endif;
            endforeach;

?>
    ])
    .addTo(map);

// zoom to layers extention

var bounds = groupFeature.getBounds();
map.fitBounds(bounds);

// legend

var baseLayers = {
    "Carto DB": CartoDB_Positron,
    "OpenStreetMap": osm,
    "Satellite": Esri
};
var overlays = {
<?php

            foreach ($item->media() as $reportGisDatasetSet):
                if ($reportGisDatasetSet->extension() == "geojson"):
                    $a = $reportGisDatasetSet->id();
                    $layerAdded = 'layerAdded'.$a;
?>
"<?php echo $reportGisDatasetSet->displayTitle() ?>": <?php echo $layerAdded ?>,

<?php
                endif;
            endforeach;

?>

};
L.control.layers(baseLayers, overlays, {position: 'bottomleft'}).addTo(map);
map.addControl(new L.Control.FitBounds(groupFeature));

</script>