<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if ((strpos($mediaType, 'image/') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>

<?php $this->trigger('view.show.before'); ?>

<div class="testContent">
    <div class="testHalf">
        <div class="contentType">
            <hr>
            <h1><i class="fas fa-cube"></i></h1>
            <hr>
        </div>
        <div class="value paragraphTitle">
            <div class="titleMenu">
                <div id="menuTitle topTitle">
                <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="allValues">
        <?php echo $item->displayValues(); ?>
            <?php if (count($otherMedia) > 0): ?>
                <div id="other-media" class="property">
                    <h4 class="fw-bold"><?php echo $this->translate('Other Media'); ?></h4>
                    <div class="values">
                        <?php foreach($otherMedia as $media): ?>
                            <div class="value">
                                <a target="_blank" href="<?php echo $media->originalUrl(); ?>" download="<?php echo $media->displayTitle(); ?>.<?php echo $media->extension(); ?>"><?php echo $media->displayTitle(); ?><?php echo " (" . $media->extension() . ", " . ceil($media->size()/1000000) . "MB)"; ?></a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
            <hr>
<!-- item linked items -->
<!-- pagination -->
            <?php $this->trigger('view.show.after'); ?>
            <hr>
        </div>
<!-- item linked items -->
        <?php echo $this->resourcePageBlocks($item, "secondary")->getBlocks(); ?>
    </div>
<!-- item 3D models -->
    <?php $template = 'omeka/site/item/show-default-models.phtml'; ?>
    <?= $this->partial($template, $this->vars()) ?>
</div>
</div>
