<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
?>

<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">

<?php
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
foreach ($this->resources as $resource):
    $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $body = $resource->value($bodyTerm);
?>

    <li class="<?php echo $this->resourceType; ?> resource">
        <?php if ($thumbnail = $this->thumbnail($resource, 'medium')): ?>
        <?php echo '<center>'; echo $resource->linkRaw($thumbnail); echo '</center>';?>
        <?php else: ?>
        <img src="<?php echo $this->assetUrl('thumbnails/no_media.png'); ?>" alt="" width="80">
        <?php endif; ?>
        <p class="customType"><b><?php echo $resource->value('dcterms:type'); ?></b></p>
        <div class='browseTitre'><center><h4><?php echo $resource->link($resource->value('dcterms:title')); ?></h4></center></div>
        <?php if ($description = $resource->value('dcterms:description')): ?>
            <div class="description">
        <?php echo mb_substr(strip_tags($description),0,60); ?>
        <?php if (strlen($description) > 59) {
            echo $resource->link('...');
            }
        ?>
        </div></br>
        <?php endif; ?>
        <?php if ($date = $resource->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div></br>
        <?php endif; ?>
    </li>
<?php endforeach; ?>

</ul>

<?php
if ($this->linkText):
    echo $this->hyperlink($this->linkText, $this->url(
        'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
    ));
endif;
?>

</div>
